### ISSUE TITLE
Titles not documented

### ISSUE THREAD

**Issue by turt2live** [chatterbox-works/Chatterbox#25]
I modified the titles section to give myself "Developer" and added some text to the general population title and got no results (see configuration below). Tried different formats to ensure it is working, no clear documentation on how to proceed.

Formats used (local was the test channel):
```
'&a[Local] &f@(playerDisplayName): @(message)'
'&a[Local] &f@(playerName): @(message)'
```

Title configuration:
```yaml
# Title options. These are ordered from highest importance to least importance.
titles:
  # Titles to apply to individuals
  individuals:
    # UUIDs should only be lowercase
    dca69745-fb06-36e3-a63d-46f0c12dac1a:
      prefix: "[Developer]"
      suffix: ""
  # Titles to apply to permission groups, if the Vault hook is installed
  groups:
    Admin:
      prefix: "[Admin]"
      suffix: ""
  # Titles to apply to everyone
  "*":
    prefix: "&a"
    suffix: ""
```
