### ISSUE TITLE
"Maximum members" doesn't work

### ISSUE THREAD

**Issue by turt2live** [chatterbox-works/Chatterbox#26]
The sample configuration has it listed on the master channel and the property is not used. Attempted to apply it to the local channel with no success (see configuration sections below).

Note: Applying a limit to the master channel is a weird thing to do, but it appears as a perfectly valid option.

Relevant master configuration properties:
```yaml
  # Maximum options
  maximum:
    # The maximum amount of members allowed to join this channel. 0 means unlimited.
    members: 1
```

Local channel declaration:
```yaml
  # A local channel. Notice that several options are not included, as the defaults match the desired functionality.
  - name: local
    tag: l
    maximum:
      members: 1
    format:
      text: '&a[Local] &f@(playerDisplayName): @(message)'
    radius:
      enabled: false
      horizontal: 36.0
      vertical: 18.0
    worlds:
      all: true
```
